In [ ]:
import torch
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

In [ ]:
dataset = pd.read_csv("/content/iris.csv")

In [ ]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
dataset_np = np.array(dataset)

data_X = dataset_np[:, 1:5]
data_Y = dataset_np[:, -1]

In [ ]:
test_ratio = 0.2

data_train, data_test = train_test_split(dataset_np, test_size=test_ratio)

In [ ]:
print(data_X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
print(data_Y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

In [ ]:
print(data_Y.shape)
label_encoder = OrdinalEncoder()
data_Y_encoded = label_encoder.fit_transform(data_Y.reshape(-1, 1))
print(data_Y_encoded.shape)

(150,)
(150, 1)


In [ ]:
print(data_X[0][0])

5.1


In [ ]:
print(type(data_X[0][0]))

<class 'float'>


In [ ]:
print(data_Y_encoded)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]]


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(data_X, data_Y_encoded, test_size=test_ratio, shuffle=True)

In [ ]:
print(x_train.shape, x_test.shape, y_train.shape , y_test.shape, )

(120, 4) (30, 4) (120, 1) (30, 1)


In [ ]:
# 4 -> 16 -> 16 -> 8 -> 3 -> [1, 0, 0] [0, 1, 0] [0, 0, 1]
class IrisModel(torch.nn.Module):
  def __init__(self):
    super(IrisModel, self).__init__()

    self.layer_1 = torch.nn.Linear(4, 16)
    self.layer_2 = torch.nn.Linear(16, 16)
    self.layer_3 = torch.nn.Linear(16, 8)
    self.layer_4 = torch.nn.Linear(8, 3)


  def forward(self, x):
    x = self.layer_1(x)
    x = self.layer_2(x)
    x = self.layer_3(x)
    x = self.layer_4(x)

    return x

In [ ]:
class IrisDataset(torch.utils.data.Dataset):
  def __init__(self, X, Y):
    super(IrisDataset, self).__init__()

    self.X = np.array(X, dtype=np.float32)
    self.Y = np.array(Y, dtype=np.int64)


  def __len__(self):
    return len(self.X) # self.X.shape[0]


  def __getitem__(self, index):
    sample_x = self.X[index]
    sample_y = self.Y[index]

    return sample_x, sample_y

In [ ]:
clf_model = IrisModel()

dataset_train = IrisDataset(x_train, y_train)
dataloader_train = torch.utils.data.DataLoader(dataset=dataset_train, batch_size=4, shuffle=True)

criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(clf_model.parameters(), lr=0.01)

iris_kfold = KFold(n_splits=5, shuffle=True)

In [ ]:
print(len(dataset_train))

120


In [ ]:
model_1 = IrisModel()

sample_input = torch.randn(8, 4)


output = model_1(sample_input)

print(sample_input.shape)
print(output.shape)

torch.Size([8, 4])
torch.Size([8, 3])


In [ ]:
sample_input = torch.randn(8, 4)

In [ ]:
def accuracy_evaluation(model, dataloader):
  ground_truth = None
  pred_labels = None

  for data, label in dataloader:
    preds = model(data)
    preds = torch.argmax(preds, dim=1)

    if pred_labels is None:
      pred_labels = preds
      ground_truth = label
    else:
      pred_labels = np.append(pred_labels, preds, axis=0)
      ground_truth = np.append(ground_truth, label, axis=0)


  # print(pred_labels)
  # print(ground_truth)
  return accuracy_score(pred_labels, ground_truth)

In [ ]:
print(accuracy_evaluation(clf_model, dataloader_train))

0.95


In [ ]:
epoch = 0
fold = 0
for train_index, test_index in iris_kfold.split(data_X):
  fold += 1
  clf_model = IrisModel()

  dataset_train = IrisDataset(data_X[train_index], data_Y_encoded[train_index])
  dataloader_train = torch.utils.data.DataLoader(dataset=dataset_train, batch_size=4, shuffle=True)

  dataset_test = IrisDataset(data_X[test_index], data_Y_encoded[test_index])
  dataloader_test = torch.utils.data.DataLoader(dataset=dataset_test, batch_size=4, shuffle=True)

  criterion = torch.nn.CrossEntropyLoss()
  optimizer = torch.optim.Adam(clf_model.parameters(), lr=0.01)

  fold_loss = list()
  for epoch in range(50):
    for data, label in dataloader_train:

      clf_model.zero_grad()

      output = clf_model(data)

      loss = criterion(output, label[:, 0])

      loss.backward()
      optimizer.step()
    # fold_list.append(loss)
  train_accuracy = accuracy_evaluation(clf_model, dataloader_train)
  test_accuracy = accuracy_evaluation(clf_model, dataloader_test )
  print(f"Fold: {fold}, Train Accuracy: {train_accuracy:.3f}, Test Accuracy: {test_accuracy:.3f}")

Fold: 1, Train Accuracy: 0.992, Test Accuracy: 0.900
Fold: 2, Train Accuracy: 0.958, Test Accuracy: 0.967
Fold: 3, Train Accuracy: 0.975, Test Accuracy: 0.967
Fold: 4, Train Accuracy: 0.975, Test Accuracy: 1.000
Fold: 5, Train Accuracy: 0.975, Test Accuracy: 1.000
